In [1]:
import numpy as np

In [113]:
id_values = [1,1,1,2,2,2,3,4,4,4,4,4]

In [114]:
d = np.random.rand(len(id_values),6)

In [115]:
d[:, 0]= id_values

In [118]:
import pandas as pd
df = pd.DataFrame(d).sort_values(by=[0,1]).reset_index(drop=True)

In [119]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [121]:
edge_index = []

In [122]:
for identifier, group in df.groupby(0):
    ## Connect all indices with all following indices in a group -> mathematical trick where you concatenate expanded triangular matrix of the index with ranged matrix (+1 trick to mask later all entries with 0)...pretty tough to explain but makes somewhat sense in my head
    print(group.index)
    offset = group.index[0]
    triu_matrix = np.triu((group.index.values + np.identity(1))[0])
    triu_exp_matrix = np.expand_dims(triu_matrix, axis=-1)

    idx_shape = group.index.shape[0]
    idx_matrix = np.ones((idx_shape, idx_shape)) * np.arange(idx_shape) + 1 + offset
    idx_matrix = np.transpose(idx_matrix)
    idx_exp_matrix = np.expand_dims(idx_matrix, axis = -1)

    unprocess_edges = np.concatenate((idx_exp_matrix, triu_exp_matrix), axis = -1)
    reshaped_unprocess_edges = np.reshape(unprocess_edges, (-1, 2))
    mask = (reshaped_unprocess_edges[:, 0]*reshaped_unprocess_edges[:, 1])!=0
    edge_index.append((reshaped_unprocess_edges[mask] -1).astype(np.int64))

Int64Index([0, 1, 2], dtype='int64')
Int64Index([3, 4, 5], dtype='int64')
Int64Index([6], dtype='int64')
Int64Index([7, 8, 9, 10, 11], dtype='int64')


In [125]:
np.concatenate(edge_index, axis = 0)

array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       [ 1,  1],
       [ 1,  2],
       [ 2,  2],
       [ 3,  3],
       [ 3,  4],
       [ 3,  5],
       [ 4,  4],
       [ 4,  5],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 7,  8],
       [ 7,  9],
       [ 7, 10],
       [ 7, 11],
       [ 8,  8],
       [ 8,  9],
       [ 8, 10],
       [ 8, 11],
       [ 9,  9],
       [ 9, 10],
       [ 9, 11],
       [10, 10],
       [10, 11],
       [11, 11]])

In [58]:
triu_matrix = np.triu(([0,1,2,3]+ np.identity(1))[0])

In [106]:
idx = [0,1,2]
idx + np.identity(1)

array([[1., 2., 3.]])

In [79]:
idx_shape = 4
idx_matrix = np.ones((idx_shape,idx_shape))* np.arange(idx_shape)+1
idx_matrix = np.transpose(idx_matrix)

In [80]:
idx_matrix, triu_matrix

(array([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]]),
 array([[1., 2., 3., 4.],
        [0., 2., 3., 4.],
        [0., 0., 3., 4.],
        [0., 0., 0., 4.]]))

In [81]:
idx_exp_matrix = np.expand_dims(idx_matrix, axis = -1)

In [82]:
triu_exp_matrix = np.expand_dims(triu_matrix, axis=-1)

In [86]:
unprocess_edges = np.concatenate((idx_exp_matrix, triu_exp_matrix), axis = -1)

In [90]:
reshaped_unprocess_edges = np.reshape(unprocess_edges, (-1, 2))

In [96]:
mask = (reshaped_unprocess_edges[:, 0]*reshaped_unprocess_edges[:, 1])!=0

In [103]:
edge_index = (reshaped_unprocess_edges[mask] -1).astype(np.int64)

In [104]:
edge_index

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 2],
       [2, 3],
       [3, 3]])